import {useState,useEffect,useRef} from 'react';
import {ArrowRight,ArrowLeft,ArrowUpRight,Clock,UsersThree,Target,Compass,Play,Plus,X,MagnifyingGlassPlus,Check} from '@phosphor-icons/react';
const A='/assets/';
const reviews=['image-2076.webp','image-2077.webp','image-2078.webp','image-2079.webp','image-2080.webp','image-2081.webp','image-2082-1.webp'];
const videos=[['OztQF1-4O58','From self-doubt to career growth','A leadership journey'],['tQm-ALyJnyA','Overcoming doubts with Job','Finding the confidence to begin'],['nTZM-UnFy2Q','Meet Spyros from Greece','A mentee’s perspective'],['H_d3lTQ25Xo','Anushri’s coaching experience','Five years of continued growth']];
const faqs=[['Who is this session for?','Senior managers, directors, VPs, and senior individual contributors with 10+ years of experience who want to work on communication, executive presence, or leadership. This is not a job placement service.'],['What does the ₹99 session cover?','A 60-minute 1-on-1 session about your current challenges, communication and leadership goals, and a recommended next step. The ₹99 fee covers the session only; any further coaching is separate and optional.'],['Will the session be with Immanuel?','The session is with the team. Immanuel leads the coaching approach; the session helps you understand which support may be right for you.'],['Do I have to join a coaching program?','No. The team may recommend a program if it fits your goals, but there is no obligation to join. Any further coaching is separate from the ₹99 session.'],['How do I book my session?','Click “Book your ₹99 session”, share your details, and complete the payment on Razorpay. Our team will then reach out to schedule your session and share joining details.']];
const SHEET_WEBHOOK_URL='https://script.google.com/macros/s/AKfycby36xA1tsykJiUVrXrk3Alb50x0y-tmti5uIMGrKE0su2oV9mKbf_e4AhtTyi5jYJf6/exec';// Paste your Google Apps Script Web App URL here (see google-apps-script/README)
const RAZORPAY_URL='https://pages.razorpay.com/pl_TWOtKi8EAol9CR/view';
function Video({video:[id,title,label],activeVideo,setActiveVideo}){const playing=activeVideo===id;return <article className="video-card"><div className="video-frame">{playing?<iframe src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1&rel=0`} title={title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowFullScreen/>:<button className="video-poster" aria-label={`Play ${title}`} onClick={()=>setActiveVideo(id)}><img src={`https://i.ytimg.com/vi/${id}/hqdefault.jpg`} alt="" width="480" height="360" loading="lazy"/><span className="play-circle"><Play size={23} weight="fill"/></span><span className="watch-label">WATCH THEIR STORY</span></button>}</div><h3>{title}</h3><p>{label}</p>{playing&&<a className="video-fallback" href={`https://www.youtube.com/watch?v=${id}`} target="_blank" rel="noopener noreferrer">Watch on YouTube <ArrowUpRight size={14}/></a>}</article>}
export function App(){
const [review,setReview]=useState(0),[modal,setModal]=useState(null),[sticky,setSticky]=useState(false),[activeVideo,setActiveVideo]=useState(null),[form,setForm]=useState({name:'',email:'',phone:''}),[submitting,setSubmitting]=useState(false);
const dialog=useRef(null),heroAction=useRef(null),utms=useRef({});
useEffect(()=>{const params=new URLSearchParams(window.location.search);const stored=sessionStorage.getItem('immanuel_utms');const found=stored?JSON.parse(stored):{};for(const k of ['utm_source','utm_medium','utm_campaign','utm_term','utm_content']){const v=params.get(k);if(v)found[k]=v}if(Object.keys(found).length)sessionStorage.setItem('immanuel_utms',JSON.stringify(found));utms.current=found},[]);
useEffect(()=>{const obs=new IntersectionObserver(([e])=>setSticky(!e.isIntersecting));if(heroAction.current)obs.observe(heroAction.current);return()=>obs.disconnect()},[]);
useEffect(()=>{if(!modal)return;const prior=document.activeElement,overflow=document.body.style.overflow;dialog.current.showModal();dialog.current.focus();document.body.style.overflow='hidden';return()=>{document.body.style.overflow=overflow;if(prior instanceof HTMLElement)prior.focus()}},[modal]);
const book=()=>setModal('booking'),close=()=>{dialog.current?.close();setModal(null)},next=d=>setReview((review+d+7)%7);
const setField=k=>e=>setForm(f=>({...f,[k]:e.target.value}));
const handleSubmit=async e=>{
e.preventDefault();
if(submitting)return;
setSubmitting(true);
const payload={...form,...utms.current,timestamp:new Date().toISOString(),page_url:window.location.href};
// keepalive lets the lead POST finish even after we navigate away, so the
// redirect to Razorpay can happen instantly instead of waiting for the sheet.
if(SHEET_WEBHOOK_URL.startsWith('https://script.google')){
fetch(SHEET_WEBHOOK_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),keepalive:true}).catch(err=>console.error('Sheet submission failed:',err));
}else{console.warn('SHEET_WEBHOOK_URL is not set — lead not saved. See google-apps-script/README.')}
window.location.assign(RAZORPAY_URL);
};
const cta=(extra='')=><button className={`button ${extra}`} onClick={book}>Book your ₹99 session <ArrowRight size={21} aria-hidden="true"/></button>;
return <><a className="skip-link" href="#main">Skip to content</a><header><div className="wrap header-inner"><a href="#" className="wordmark">IMMANUEL <span>WILLIAMS</span><small>LEADERSHIP & COMMUNICATION</small></a><nav aria-label="Main navigation"><a href="#consultation">The session</a><a href="#stories">Client stories</a><a href="#faqs">FAQs</a></nav><button className="header-cta" onClick={book}>Book a session <ArrowUpRight size={17}/></button></div></header>
<main id="main"><section className="hero"><div className="wrap hero-inner"><div className="hero-copy"><p className="eyebrow">FOR SENIOR PROFESSIONALS · 10+ YEARS OF EXPERIENCE</p><h1>Build the presence<br className="desktop-break"/> your experience <span>deserves.</span></h1><p className="hero-description">A 60-minute 1-on-1 session to identify your communication and leadership gaps — and clarify your next step.</p><div ref={heroAction} className="hero-action">{cta()}<p className="offer-note"><Clock size={17}/>60-minute 1-on-1 · with our team</p></div><p className="hero-footnote">Your experience is the foundation. Let’s build on it.</p></div><div className="hero-portrait"><picture><source media="(max-width:600px)" srcSet={A+'ChatGPT-Image-Aug-26-2026-03_08_51-PM-1.webp'}/><img src={A+'ChatGPT-Image-Aug-26-2026-03_08_51-PM.webp'} alt="Immanuel Williams, leadership and communication coach" width="1942" height="816" fetchPriority="high"/></picture><div className="portrait-caption"><strong>Immanuel Williams</strong><span>Leadership Coach & Founder</span></div></div></div></section>
<section id="consultation" className="takeaways light"><div className="wrap"><div className="section-intro"><p className="eyebrow">ONE SESSION. THREE CONCRETE TAKEAWAYS.</p><h2>What you’ll leave the session with.</h2></div><div className="takeaway-grid">{[[UsersThree,'A clearer view of the challenge','Pinpoint where your communication or leadership presence is falling short today.'],[Target,'Your first priority','The one gap worth working on before anything else.'],[Compass,'A recommended next step','A practical direction based on your goals — not a generic plan.']].map(([Icon,title,text])=><article className="takeaway" key={title}><div className="icon-disc"><Icon size={29}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="stories" className="stories section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">IN THEIR OWN WORDS</p><h2>Real people.<br className="mobile-only"/> Personal progress.</h2></div><p>Experiences from our coaching programs.<br/>A closer look at the work beyond the first call.</p></div><div className="proof-grid"><div className="reviews-column"><div className="subheading"><span>CLIENT REVIEWS</span><span className="count" aria-live="polite">{String(review+1).padStart(2,'0')} / 07</span></div><button className="review-image" onClick={()=>setModal('review')} aria-label={`Enlarge client review ${review+1} of 7`}><img src={A+reviews[review]} alt={`Original client review ${review+1} of 7; open to read full size`} width="1086" height="914" loading="lazy"/><span><MagnifyingGlassPlus size={16}/>Tap to read full review</span></button><div className="review-controls"><button className="round-button" onClick={()=>next(-1)} aria-label="Previous review"><ArrowLeft size={20}/></button><div className="review-dots">{reviews.map((_,i)=><button key={i} onClick={()=>setReview(i)} aria-label={`Show review ${i+1}`} aria-current={i===review?'true':undefined} className={i===review?'active':''}><span/></button>)}</div><button className="round-button" onClick={()=>next(1)} aria-label="Next review"><ArrowRight size={20}/></button></div></div><div className="videos-column"><div className="subheading"><span>VIDEO STORIES</span><span className="count">04 STORIES</span></div><div className="videos-grid">{videos.map(v=><Video key={v[0]} video={v} activeVideo={activeVideo} setActiveVideo={setActiveVideo}/>)}</div></div></div><div className="proof-cta"><p>Ready to talk about your own next step?</p>{cta('button-outline')}</div></div></section>
<section id="coach" className="coach-section"><div className="wrap coach-grid"><div className="coach-photos"><img className="coach-photo" src={A+'1A8A0913-scaled-1.webp'} alt="Immanuel Williams at his office" width="600" height="400" loading="lazy"/></div><div className="coach-copy"><p className="eyebrow">THE PERSON BEHIND THE PRACTICE</p><h2>Meet Immanuel.</h2><p>Leadership Coach & Founder</p><p>Immanuel’s approach connects communication, mindset, and leadership with the situations professionals face every day.</p><p>The focus is personal: practice, feedback, and applying what you learn to your real working life.</p><div className="coach-note"><Check size={19}/><span>Your first consultation is with the team, to explore your goals and the right fit.</span></div></div></div></section>
<section className="how-section light section"><div className="wrap"><div className="section-intro"><p className="eyebrow">HOW IT WORKS</p><h2>Four steps to your first session.</h2></div><div className="steps">{[['Book your session','Share your details and complete the ₹99 payment to reserve your session.'],['Pre-session conversation','A short call with our team to understand your role, challenges, and goals.'],['Attend your 1-on-1 session','A focused 60-minute session to identify your skill patterns and gaps.'],['Decide your path','If you find value, you can continue into coaching. Entirely optional.']].map(([title,text],i)=><article className="step" key={title}><span className="step-number">0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div><p className="price-clarity">₹99 covers the session. Further coaching is separate and entirely optional.</p></div></section>
<section id="faqs" className="faqs section"><div className="wrap faq-grid"><div><p className="eyebrow">BEFORE YOU BOOK</p><h2>A little more<br/>clarity.</h2><p>Good decisions start with good questions.</p></div><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<Plus size={20}/></summary><p>{a}</p></details>)}</div></div></section>
<section className="final-cta"><div className="wrap"><p className="eyebrow">EVERY CAREER IS DIFFERENT. ONE PLAN DOESN’T FIT ALL.</p><h2>Your situation is specific.<br className="mobile-only"/> Your session should be too.</h2><p>Bring your experience and your questions.<br/>Leave with a recommended next step.</p>{cta()}<p className="offer-note"><Clock size={17}/>60 minutes · ₹99 · 1-on-1 with our team</p></div></section></main>
<footer><div className="wrap footer-inner"><div className="wordmark">IMMANUEL <span>WILLIAMS</span><small>LEADERSHIP & COMMUNICATION</small></div><div className="footer-links"><a href="https://immanuelwilliams.com/privacy-policy/" target="_blank" rel="noopener noreferrer">Privacy policy</a><a href="https://immanuelwilliams.com/terms-conditions/" target="_blank" rel="noopener noreferrer">Terms & conditions</a><a href="https://immanuelwilliams.com/refund_returns/" target="_blank" rel="noopener noreferrer">Refund policy</a></div><p>© {new Date().getFullYear()} Immanuel Williams</p></div></footer>
<aside className={`mobile-booking ${sticky&&!modal?'visible':''}`} aria-label="Book a consultation" inert={!sticky||!!modal?true:undefined}><div><strong>₹99</strong><span>60-minute session</span></div><button className="button" onClick={book}>Book a session <ArrowRight size={19}/></button></aside>
{modal&&<dialog ref={dialog} tabIndex={-1} className={`modal ${modal==='review'?'review-modal':''}`} onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}} aria-labelledby="modal-title"><button className="close-button" onClick={close} aria-label="Close dialog"><X size={23}/></button>{modal==='review'?<><h2 id="modal-title">Client review {review+1} of 7</h2><img src={A+reviews[review]} alt={`Full original client review ${review+1}`}/><div className="modal-review-controls"><button className="round-button" aria-label="Previous full review" onClick={()=>next(-1)}><ArrowLeft size={20}/></button><a href={A+reviews[review]} target="_blank" rel="noopener noreferrer">Open original image <ArrowUpRight size={16}/></a><button className="round-button" aria-label="Next full review" onClick={()=>next(1)}><ArrowRight size={20}/></button></div></>:<><p className="eyebrow">BOOK YOUR 1-ON-1 SESSION</p><h2 id="modal-title">Your next step,<br/>a little clearer.</h2><p>Share your details — our team will schedule your session after payment.</p><div className="booking-summary">{[['Session fee','₹99'],['Duration','60 minutes'],['Format','1-on-1 with our team']].map(([a,b])=><div key={a}><span>{a}</span><strong>{b}</strong></div>)}</div><form className="booking-form" onSubmit={handleSubmit}><div className="field"><label htmlFor="bf-name">Full name</label><input id="bf-name" name="name" type="text" required autoComplete="name" placeholder="Your name" value={form.name} onChange={setField('name')}/></div><div className="field"><label htmlFor="bf-email">Email</label><input id="bf-email" name="email" type="email" required autoComplete="email" placeholder="you@example.com" value={form.email} onChange={setField('email')}/></div><div className="field"><label htmlFor="bf-phone">Phone (WhatsApp)</label><input id="bf-phone" name="phone" type="tel" required autoComplete="tel" inputMode="tel" pattern="[0-9+\\s-]{10,15}" placeholder="10-digit mobile number" value={form.phone} onChange={setField('phone')}/></div><button className="button" type="submit" disabled={submitting}>{submitting?'Securing your slot…':'Pay ₹99 & book my slot'} <ArrowRight size={20} aria-hidden="true"/></button><p className="booking-helper">You’ll continue to a secure Razorpay page to complete the ₹99 payment. We use your details only to schedule and run your session.</p></form><p className="booking-terms">Further coaching is optional and priced separately.</p></>}</dialog>}</>}
